title: MatheChecks
description: "Interaktive, kostenlose Mathe-Übungen und Erklärungen für Analysis, Stochastik und lineare Algebra."

author: "Dr. Sven Führing"
url: "https://www.mathechecks.de"
baseurl: ""

lang: de_DE

port: 4001 # Port für den lokalen Server ohne Admin

plugins:
  - jekyll-seo-tag

exclude:
  - functions
  - xls
  - html
