title: MatheChecks

author: "Dr. Sven Führing"
url: "https://mathedoc.github.io"
baseurl: ""

lang: de_DE

port: 4001 # Port für den lokalen Server ohne Admin

plugins:
  - jekyll-seo-tag

exclude:
  - functions
  - xls
  - html
