title: MatheChecks
description: "Interaktive, kostenlose Mathe-Übungen und Erklärungen für Analysis, Stochastik und lineare Algebra."

author: "Dr. Sven Führing"
url: "https://www.mathechecks.de"
baseurl: ""

firebase_api_key: "AIzaSyBAnzmTARIyzvuHGxHWhqlqRYiLPjRRkyI"
firebase_auth_domain: "mathechecks-c1e86.firebaseapp.com"
firebase_project_id: "mathechecks-c1e86"

lang: de_DE

markdown: kramdown
kramdown:
  input: Kramdown
  math_engine: mathjax

port: 4001 # Port für den lokalen Server ohne Admin

plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: "dev"
      type: "pages"
    values:
      published: true

exclude:
  - functions
  - xls
  - html

