from dataclasses import dataclass, field


@dataclass(frozen=True)
class ABScenarioTemplate:
    intro: str
    event_a: str
    event_b: str
    # Textbausteine für "die Wahrscheinlichkeit, dass ..."
    # Werden in Check 4 (Ablesen/Berechnen) genutzt.
    prob_texts: dict[str, str] = field(default_factory=dict)
    # Schlüssel: pa, pna, pb, pnb,
    #            pab, panb, pnab, pnanb,
    #            paub, paunb, pnaub, pnaunb,
    #            pba, pnba, pbna, pnbna,
    #            pab_c, pnab_c, panb_c, pnanb_c
    # Formulierung der stochastischen Unabhängigkeit (kontextbezogen)
    independence_claim: str = ""
    # Formulierung der stochastischen Abhängigkeit (kontextbezogen)
    dependence_claim: str = ""


SCENARIOS: list[ABScenarioTemplate] = [
    # 1) Halbleiter
    ABScenarioTemplate(
        intro="Ein Hersteller von Halbleitern erhält Aufträge von Groß- und Kleinkunden. Alle Kunden können zwischen Basis- und Premium-Qualität wählen.",
        event_a="Ein Großkunde bestellt Halbleiter.",
        event_b="Halbleiter werden in Premium-Qualität bestellt.",
        prob_texts={
            "pa": "ein Großkunde Halbleiter bestellt",
            "pna": "ein Kleinkunde Halbleiter bestellt",
            "pb": "Halbleiter in Premium-Qualität bestellt werden",
            "pnb": "Halbleiter in Basis-Qualität bestellt werden",
            "pab": "eine Bestellung von einem Großkunden stammt und Premium-Qualität erfordert",
            "panb": "eine Bestellung von einem Großkunden stammt und Basis-Qualität erfordert",
            "pnab": "eine Bestellung von einem Kleinkunden stammt und Premium-Qualität erfordert",
            "pnanb": "eine Bestellung von einem Kleinkunden stammt und Basis-Qualität erfordert",
            "paub": "ein Großkunde Halbleiter bestellt oder Halbleiter in Premium-Qualität bestellt werden",
            "paunb": "ein Großkunde Halbleiter bestellt oder Halbleiter in Basis-Qualität bestellt werden",
            "pnaub": "ein Kleinkunde Halbleiter bestellt oder Halbleiter in Premium-Qualität bestellt werden",
            "pnaunb": "ein Kleinkunde Halbleiter bestellt oder Halbleiter in Basis-Qualität bestellt werden",
            "pba": "der Auftrag eines Großkunden Premium-Qualität erfordert",
            "pnba": "der Auftrag eines Großkunden Basis-Qualität erfordert",
            "pbna": "der Auftrag eines Kleinkunden Premium-Qualität erfordert",
            "pnbna": "der Auftrag eines Kleinkunden Basis-Qualität erfordert",
            "pab_c": "ein Auftrag in Premium-Qualität von einem Großkunden stammt",
            "pnab_c": "ein Auftrag in Premium-Qualität von einem Kleinkunden stammt",
            "panb_c": "ein Auftrag in Basis-Qualität von einem Großkunden stammt",
            "pnanb_c": "ein Auftrag in Basis-Qualität von einem Kleinkunden stammt",
        },
        independence_claim="Die Art eines Kunden hat keine Auswirkung auf die Qualität der bestellten Halbleiter.",
        dependence_claim="Die Art eines Kunden hat eine Auswirkung auf die Qualität der bestellten Halbleiter.",
    ),
    # 2) Zugbegleiterin
    ABScenarioTemplate(
        intro="Eine Zugbegleiterin kontrolliert die Fahrscheine und das Einhalten der Maskenpflicht in einem ICE von Hamburg nach München.",
        event_a="Ein Passagier hat einen gültigen Fahrschein.",
        event_b="Ein Passagier trägt eine Maske.",
        prob_texts={
            "pa": "ein Passagier einen gültigen Fahrschein hat",
            "pna": "ein Passagier keinen gültigen Fahrschein hat",
            "pb": "ein Passagier eine Maske trägt",
            "pnb": "ein Passagier keine Maske trägt",
            "pab": "ein Passagier einen gültigen Fahrschein hat und eine Maske trägt",
            "panb": "ein Passagier einen gültigen Fahrschein hat und keine Maske trägt",
            "pnab": "ein Passagier keinen gültigen Fahrschein hat und eine Maske trägt",
            "pnanb": "ein Passagier keinen gültigen Fahrschein hat und keine Maske trägt",
            "paub": "ein Passagier einen gültigen Fahrschein hat oder eine Maske trägt",
            "paunb": "ein Passagier einen gültigen Fahrschein hat oder keine Maske trägt",
            "pnaub": "ein Passagier keinen gültigen Fahrschein hat oder eine Maske trägt",
            "pnaunb": "ein Passagier keinen gültigen Fahrschein hat oder keine Maske trägt",
            "pba": "ein Passagier mit gültigem Fahrschein eine Maske trägt",
            "pnba": "ein Passagier mit gültigem Fahrschein keine Maske trägt",
            "pbna": "ein Passagier ohne gültigen Fahrschein eine Maske trägt",
            "pnbna": "ein Passagier ohne gültigen Fahrschein keine Maske trägt",
            "pab_c": "ein Passagier, der eine Maske trägt, auch einen gültigen Fahrschein hat",
            "pnab_c": "ein Passagier, der eine Maske trägt, keinen gültigen Fahrschein hat",
            "panb_c": "ein Passagier, der keine Maske trägt, einen gültigen Fahrschein hat",
            "pnanb_c": "ein Passagier, der keine Maske trägt, auch keinen gültigen Fahrschein hat",
        },
        independence_claim="Ob ein Passagier einen gültigen Fahrschein besitzt oder nicht, hat keinen Einfluss darauf, ob er eine Maske trägt.",
        dependence_claim="Ob ein Passagier einen gültigen Fahrschein besitzt oder nicht, hat einen Einfluss darauf, ob er eine Maske trägt.",
    ),
    # 3) Eisstand
    ABScenarioTemplate(
        intro="Ein Eisstand bietet Getränke an: Schokolade und Kaffee, jeweils entweder heiß oder kalt zubereitet.",
        event_a="Ein Kunde bestellt eine Schokolade.",
        event_b="Ein Kunde bestellt ein heißes Getränk.",
        prob_texts={
            "pa": "ein Kunde eine Schokolade bestellt",
            "pna": "ein Kunde einen Kaffee bestellt",
            "pb": "ein Kunde ein heißes Getränk bestellt",
            "pnb": "ein Kunde ein kaltes Getränk bestellt",
            "pab": "ein Kunde eine heiße Schokolade bestellt",
            "panb": "ein Kunde eine Eisschokolade bestellt",
            "pnab": "ein Kunde einen heißen Kaffee bestellt",
            "pnanb": "ein Kunde einen Eiskaffee bestellt",
            "paub": "ein Kunde eine Schokolade oder ein heißes Getränk bestellt",
            "paunb": "ein Kunde eine Schokolade oder ein kaltes Getränk bestellt",
            "pnaub": "ein Kunde einen Kaffee oder ein heißes Getränk bestellt",
            "pnaunb": "ein Kunde einen Kaffee oder ein kaltes Getränk bestellt",
            "pba": "eine bestellte Schokolade heiß erwünscht ist",
            "pnba": "eine bestellte Schokolade kalt erwünscht ist",
            "pbna": "ein bestellter Kaffee heiß erwünscht ist",
            "pnbna": "ein bestellter Kaffee kalt erwünscht ist",
            "pab_c": "ein bestelltes heißes Getränk eine Schokolade ist",
            "pnab_c": "ein bestelltes heißes Getränk ein Kaffee ist",
            "panb_c": "ein bestelltes kaltes Getränk eine Schokolade ist",
            "pnanb_c": "ein bestelltes kaltes Getränk ein Kaffee ist",
        },
        independence_claim="Die Wahl eines bestellten Getränks beeinflusst nicht die gewünschte Temperatur.",
        dependence_claim="Die Wahl eines bestellten Getränks beeinflusst die gewünschte Temperatur.",
    ),
    # 4) Würfel
    ABScenarioTemplate(
        intro="Ein angeblich verzauberter Würfel wird geworfen. Bevor man wirft, kann man einen Zauberspruch aufsagen.",
        event_a="Es wird eine Sechs geworfen.",
        event_b="Es wird ein Zauberspruch aufgesagt.",
        prob_texts={
            "pa": "eine Sechs geworfen wird",
            "pna": "keine Sechs geworfen wird",
            "pb": "ein Zauberspruch aufgesagt wird",
            "pnb": "kein Zauberspruch aufgesagt wird",
            "pab": "eine Sechs geworfen und ein Zauberspruch aufgesagt wird",
            "panb": "eine Sechs geworfen und kein Zauberspruch aufgesagt wird",
            "pnab": "keine Sechs geworfen und ein Zauberspruch aufgesagt wird",
            "pnanb": "keine Sechs geworfen und kein Zauberspruch aufgesagt wird",
            "paub": "eine Sechs geworfen oder ein Zauberspruch aufgesagt wird",
            "paunb": "eine Sechs geworfen oder kein Zauberspruch aufgesagt wird",
            "pnaub": "keine Sechs geworfen oder ein Zauberspruch aufgesagt wird",
            "pnaunb": "keine Sechs geworfen oder kein Zauberspruch aufgesagt wird",
            "pba": "ein Zauberspruch aufgesagt wurde, wenn eine Sechs geworfen wird",
            "pnba": "kein Zauberspruch aufgesagt wurde, wenn eine Sechs geworfen wird",
            "pbna": "ein Zauberspruch aufgesagt wurde, wenn keine Sechs geworfen wird",
            "pnbna": "kein Zauberspruch aufgesagt wurde, wenn keine Sechs geworfen wird",
            "pab_c": "eine Sechs geworfen wird, wenn ein Zauberspruch aufgesagt wurde",
            "pnab_c": "keine Sechs geworfen wird, wenn ein Zauberspruch aufgesagt wurde",
            "panb_c": "eine Sechs geworfen wird, wenn kein Zauberspruch aufgesagt wurde",
            "pnanb_c": "keine Sechs geworfen wird, wenn kein Zauberspruch aufgesagt wurde",
        },
        independence_claim="Der Zauberspruch wirkt nicht.",
        dependence_claim="Der Zauberspruch wirkt.",
    ),
    # 5) Bundesbank
    ABScenarioTemplate(
        intro="Für das Controlling bei der Deutschen Bundesbank bewerben sich Mathematiker und Wirtschaftswissenschaftler mit Bachelor- oder Masterabschluss.",
        event_a="Ein Bewerber ist Mathematiker.",
        event_b="Ein Bewerber hat einen Bachelor.",
        prob_texts={
            "pa": "ein Bewerber Mathematiker ist",
            "pna": "ein Bewerber Wirtschaftswissenschaftler ist",
            "pb": "ein Bewerber einen Bachelor hat",
            "pnb": "ein Bewerber einen Master hat",
            "pab": "ein Bewerber einen Bachelor in Mathematik hat",
            "panb": "ein Bewerber einen Master in Mathematik hat",
            "pnab": "ein Bewerber einen Bachelor in Wirtschaftswissenschaft hat",
            "pnanb": "ein Bewerber einen Master in Wirtschaftswissenschaften hat",
            "paub": "ein Bewerber Mathematiker ist oder einen Bachelor hat",
            "paunb": "ein Bewerber Mathematiker ist oder einen Master hat",
            "pnaub": "ein Bewerber Wirtschaftswissenschaftler ist oder einen Bachelor hat",
            "pnaunb": "ein Bewerber Wirtschaftswissenschaftler ist oder einen Master hat",
            "pba": "ein Mathematiker einen Bachelor hat",
            "pnba": "ein Mathematiker einen Master hat",
            "pbna": "ein Wirtschaftswissenschaftler einen Bachelor hat",
            "pnbna": "ein Wirtschaftswissenschaftler einen Master hat",
            "pab_c": "ein Bewerber mit Bachelor Mathematiker ist",
            "pnab_c": "ein Bewerber mit Bachelor Wirtschaftswissenschaftler ist",
            "panb_c": "ein Bewerber mit Master Mathematiker ist",
            "pnanb_c": "ein Bewerber mit Master Wirtschaftswissenschaftler ist",
        },
        independence_claim="Die Fachrichtung eines Bewerbers hat keinen Einfluss darauf, ob der Bewerber einen Bachelor oder Master hat.",
        dependence_claim="Die Fachrichtung eines Bewerbers hat einen Einfluss darauf, ob der Bewerber einen Bachelor oder Master hat.",
    ),
    # 6) Führerscheinprüfung
    ABScenarioTemplate(
        intro="Bei der praktischen Führerscheinprüfung wird untersucht, ob der Gemütszustand des Prüfers das Ergebnis beeinflusst.",
        event_a="Der Prüfling besteht.",
        event_b="Der Prüfer ist ausgeschlafen.",
        prob_texts={
            "pa": "ein Prüfling besteht",
            "pna": "ein Prüfling durchfällt",
            "pb": "ein Prüfer ausgeschlafen ist",
            "pnb": "ein Prüfer nicht ausgeschlafen ist",
            "pab": "ein Prüfling besteht und ein Prüfer ausgeschlafen ist",
            "panb": "ein Prüfling besteht und ein Prüfer nicht ausgeschlafen ist",
            "pnab": "ein Prüfling durchfällt und ein Prüfer ausgeschlafen ist",
            "pnanb": "ein Prüfling durchfällt und ein Prüfer nicht ausgeschlafen ist",
            "paub": "ein Prüfling besteht oder ein Prüfer ausgeschlafen ist",
            "paunb": "ein Prüfling besteht oder ein Prüfer nicht ausgeschlafen ist",
            "pnaub": "ein Prüfling durchfällt oder ein Prüfer ausgeschlafen ist",
            "pnaunb": "ein Prüfling durchfällt oder ein Prüfer nicht ausgeschlafen ist",
            "pba": "ein Prüfer ausgeschlafen ist, wenn ein Prüfling besteht",
            "pnba": "ein Prüfer nicht ausgeschlafen ist, wenn ein Prüfling besteht",
            "pbna": "ein Prüfer ausgeschlafen ist, wenn ein Prüfling durchfällt",
            "pnbna": "ein Prüfer nicht ausgeschlafen ist, wenn ein Prüfling durchfällt",
            "pab_c": "bei einem ausgeschlafenen Prüfer ein Prüfling besteht",
            "pnab_c": "bei einem ausgeschlafenen Prüfer ein Prüfling durchfällt",
            "panb_c": "bei einem nicht ausgeschlafenen Prüfer ein Prüfling besteht",
            "pnanb_c": "bei einem nicht ausgeschlafenen Prüfer ein Prüfling durchfällt",
        },
        independence_claim="Es gibt keinen Zusammenhang zwischen dem Bestehen einer Prüfung und der Müdigkeit eines Prüfers.",
        dependence_claim="Es gibt einen Zusammenhang zwischen dem Bestehen einer Prüfung und der Müdigkeit eines Prüfers.",
    ),
    # 7) Hanteln
    ABScenarioTemplate(
        intro="In einem Sportgeschäft werden Hanteln aus Metall und Kunststoff angeboten. Zur Schonung der Handgelenke sind einige Hanteln zudem mit einem drehbaren Griff ausgestattet.",
        event_a="Eine Hantel ist aus Metall.",
        event_b="Eine Hantel hat einen drehbaren Griff.",
        prob_texts={
            "pa": "eine Hantel aus Metall ist",
            "pna": "eine Hantel aus Kunststoff ist",
            "pb": "eine Hantel einen drehbaren Griff hat",
            "pnb": "eine Hantel keinen drehbaren Griff hat",
            "pab": "eine Hantel aus Metall ist und einen drehbaren Griff hat",
            "panb": "eine Hantel aus Metall ist und keinen drehbaren Griff hat",
            "pnab": "eine Hantel aus Kunststoff ist und einen drehbaren Griff hat",
            "pnanb": "eine Hantel aus Kunststoff ist und keinen drehbaren Griff hat",
            "paub": "eine Hantel aus Metall ist oder einen drehbaren Griff hat",
            "paunb": "eine Hantel aus Metall ist oder keinen drehbaren Griff hat",
            "pnaub": "eine Hantel aus Kunststoff ist oder einen drehbaren Griff hat",
            "pnaunb": "eine Hantel aus Kunststoff ist oder keinen drehbaren Griff hat",
            "pba": "eine Metallhantel einen drehbaren Griff hat",
            "pnba": "eine Metallhantel keinen drehbaren Griff hat",
            "pbna": "eine Kunststoffhantel einen drehbaren Griff hat",
            "pnbna": "eine Kunststoffhantel keinen drehbaren Griff hat",
            "pab_c": "eine Hantel mit drehbarem Griff aus Metall ist",
            "pnab_c": "eine Hantel mit drehbarem Griff aus Kunststoff ist",
            "panb_c": "eine Hantel ohne drehbaren Griff aus Metall ist",
            "pnanb_c": "eine Hantel ohne drehbaren Griff aus Kunststoff ist",
        },
        independence_claim="Das Material einer Hantel beeinflusst nicht die Art des Griffes.",
        dependence_claim="Das Material einer Hantel beeinflusst die Art des Griffes.",
    ),
    # 8) Fußballspielerin
    ABScenarioTemplate(
        intro="Eine Fußballspielerin nimmt vor einigen Spielen Doping ein. Spiele können entweder gewonnen oder verloren werden.",
        event_a="Sie gewinnt ein Spiel.",
        event_b="Sie dopt in einem Spiel.",
        prob_texts={
            "pa": "sie ein Spiel gewinnt",
            "pna": "sie ein Spiel verliert",
            "pb": "sie in einem Spiel dopt",
            "pnb": "sie in einem Spiel nicht dopt",
            "pab": "sie ein Spiel gewinnt und dopt",
            "panb": "sie ein Spiel gewinnt und nicht dopt",
            "pnab": "sie ein Spiel verliert und dopt",
            "pnanb": "sie ein Spiel verliert und nicht dopt",
            "paub": "sie ein Spiel gewinnt oder dopt",
            "paunb": "sie ein Spiel gewinnt oder nicht dopt",
            "pnaub": "sie ein Spiel verliert oder dopt",
            "pnaunb": "sie ein Spiel verliert oder nicht dopt",
            "pba": "sie in einem gewonnenen Spiel gedopt hat",
            "pnba": "sie in einem gewonnenen Spiel nicht gedopt hat",
            "pbna": "sie in einem verlorenen Spiel gedopt hat",
            "pnbna": "sie in einem verlorenen Spiel nicht gedopt hat",
            "pab_c": "sie unter Dopingeinfluss ein Spiel gewinnt",
            "pnab_c": "sie unter Dopingeinfluss ein Spiel verliert",
            "panb_c": "sie ein Spiel, in dem sie nicht gedopt hat, gewinnt",
            "pnanb_c": "sie ein Spiel, in dem sie nicht gedopt hat, verliert",
        },
        independence_claim="Doping hat keinen Einfluss auf die Leistung der Fußballspielerin.",
        dependence_claim="Doping hat einen Einfluss auf die Leistung der Fußballspielerin.",
    ),
    # 9) Home-Office
    ABScenarioTemplate(
        intro="Ein Unternehmen stellt fest, ob seine Mitarbeiter im Home-Office oder in Präsenz arbeiten. Es gibt Voll- und Teilzeitkräfte.",
        event_a="Ein Mitarbeiter arbeitet im Home-Office.",
        event_b="Ein Mitarbeiter arbeitet in Vollzeit.",
        prob_texts={
            "pa": "ein Mitarbeiter im Home-Office arbeitet",
            "pna": "ein Mitarbeiter in Präsenz arbeitet",
            "pb": "ein Mitarbeiter in Vollzeit arbeitet",
            "pnb": "ein Mitarbeiter in Teilzeit arbeitet",
            "pab": "ein Mitarbeiter in Vollzeit und im Home-Office arbeitet",
            "panb": "ein Mitarbeiter in Teilzeit und im Home-Office arbeitet",
            "pnab": "ein Mitarbeiter in Vollzeit und in Präsenz arbeitet",
            "pnanb": "ein Mitarbeiter in Teilzeit und in Präsenz arbeitet",
            "paub": "ein Mitarbeiter im Home-Office oder in Vollzeit arbeitet",
            "paunb": "ein Mitarbeiter im Home-Office oder in Teilzeit arbeitet",
            "pnaub": "ein Mitarbeiter in Präsenz oder in Vollzeit arbeitet",
            "pnaunb": "ein Mitarbeiter in Präsenz oder in Teilzeit arbeitet",
            "pba": "ein Mitarbeiter im Home-Office in Vollzeit arbeitet",
            "pnba": "ein Mitarbeiter im Home-Office in Teilzeit arbeitet",
            "pbna": "ein Mitarbeiter in Präsenz in Vollzeit arbeitet",
            "pnbna": "ein Mitarbeiter in Präsenz in Teilzeit arbeitet",
            "pab_c": "eine Vollzeitkraft im Home-Office arbeitet",
            "pnab_c": "eine Vollzeitkraft in Präsenz arbeitet",
            "panb_c": "eine Teilzeitkraft im Home-Office arbeitet",
            "pnanb_c": "eine Teilzeitkraft in Präsenz arbeitet",
        },
        independence_claim="Es gibt keinen Zusammenhang zwischen der Arbeitsstätte und dem Umfang der Arbeitszeit.",
        dependence_claim="Es gibt einen Zusammenhang zwischen der Arbeitsstätte und dem Umfang der Arbeitszeit.",
    ),
    # 10) Restaurants
    ABScenarioTemplate(
        intro="Die Geschäftsleitung eines Restaurants interessiert sich dafür, wie kinderfreundlich die konkurrierenden Restaurants der Stadt sind.",
        event_a="Ein Restaurant hat einen Biergarten.",
        event_b="Ein Restaurant hat eine Spielecke.",
        prob_texts={
            "pa": "ein Restaurant über einen Biergarten verfügt",
            "pna": "ein Restaurant über keinen Biergarten verfügt",
            "pb": "ein Restaurant über eine Spielecke verfügt",
            "pnb": "ein Restaurant über keine Spielecke verfügt",
            "pab": "ein Restaurant über einen Biergarten und eine Spielecke verfügt",
            "panb": "ein Restaurant über einen Biergarten aber über keine Spielecke verfügt",
            "pnab": "ein Restaurant über keinen Biergarten aber über eine Spielecke verfügt",
            "pnanb": "ein Restaurant weder über einen Biergarten noch über eine Spielecke verfügt",
            "paub": "ein Restaurant über einen Biergarten oder eine Spielecke verfügt",
            "paunb": "ein Restaurant über einen Biergarten oder über keine Spielecke verfügt",
            "pnaub": "ein Restaurant über keinen Biergarten oder über eine Spielecke verfügt",
            "pnaunb": "ein Restaurant über keinen Biergarten oder über keine Spielecke verfügt",
            "pba": "ein Restaurant mit Biergarten über eine Spielecke verfügt",
            "pnba": "ein Restaurant mit Biergarten über keine Spielecke verfügt",
            "pbna": "ein Restaurant ohne Biergarten über eine Spielecke verfügt",
            "pnbna": "ein Restaurant ohne Biergarten über keine Spielecke verfügt",
            "pab_c": "ein Restaurant mit Spielecke über einen Biergarten verfügt",
            "pnab_c": "ein Restaurant mit Spielecke über keinen Biergarten verfügt",
            "panb_c": "ein Restaurant ohne Spielecke über einen Biergarten verfügt",
            "pnanb_c": "ein Restaurant ohne Spielecke über keinen Biergarten verfügt",
        },
        independence_claim="Ob ein Restaurant einen Biergarten hat oder nicht, hat keinen Einfluss darauf, ob es auch über eine Spielecke verfügt.",
        dependence_claim="Ob ein Restaurant einen Biergarten hat oder nicht, hat einen Einfluss darauf, ob es auch über eine Spielecke verfügt.",
    ),
    # 11) Holzkohle
    ABScenarioTemplate(
        intro="In einem Gartencenter wird konventionelle und nachhaltige Holzkohle angeboten. Beide Kohlearten sind als teure Originalprodukte oder günstige Nachahmerprodukte erhältlich.",
        event_a="Ein Kunde kauft nachhaltige Holzkohle.",
        event_b="Ein Kunde kauft ein Originalprodukt.",
        prob_texts={
            "pa": "ein Kunde nachhaltige Holzkohle kauft",
            "pna": "ein Kunde konventionelle Holzkohle kauft",
            "pb": "ein Kunde ein Originalprodukt kauft",
            "pnb": "ein Kunde ein Nachahmerprodukt kauft",
            "pab": "ein Kunde ein nachhaltiges Originalprodukt kauft",
            "panb": "ein Kunde ein nachhaltiges Nachahmerprodukt kauft",
            "pnab": "ein Kunde ein konventionelles Originalprodukt kauft",
            "pnanb": "ein Kunde ein konventionelles Nachahmerprodukt kauft",
            "paub": "ein Kunde nachhaltige Holzkohle oder ein Originalprodukt kauft",
            "paunb": "ein Kunde nachhaltige Holzkohle oder ein Nachahmerprodukt kauft",
            "pnaub": "ein Kunde konventionelle Holzkohle oder ein Originalprodukt kauft",
            "pnaunb": "ein Kunde konventionelle Holzkohle oder ein Nachahmerprodukt kauft",
            "pba": "gekaufte nachhaltige Holzkohle ein Originalprodukt ist",
            "pnba": "gekaufte nachhaltige Holzkohle ein Nachahmerprodukt ist",
            "pbna": "gekaufte konventionelle Holzkohle ein Originalprodukt ist",
            "pnbna": "gekaufte konventionelle Holzkohle ein Nachahmerprodukt ist",
            "pab_c": "ein gekauftes Originalprodukt nachhaltig ist",
            "pnab_c": "ein gekauftes Originalprodukt konventionell ist",
            "panb_c": "ein gekauftes Nachahmerprodukt nachhaltig ist",
            "pnanb_c": "ein gekauftes Nachahmerprodukt konventionell ist",
        },
        independence_claim="Die Ökobilanz der gekauften Holzkohle hat keinen Effekt darauf, ob es sich um ein Original- oder Nachahmerprodukt handelt.",
        dependence_claim="Die Ökobilanz der gekauften Holzkohle hat einen Effekt darauf, ob es sich um ein Original- oder Nachahmerprodukt handelt.",
    ),
    # 12) Wandfarbe
    ABScenarioTemplate(
        intro="Ein Geschäft für Heimwerkerbedarf bietet Wandfarbe in den Farben weiß und beige an, jeweils entweder matt oder glänzend. Genau ein Produkt ist im Sonderangebot.",
        event_a="Weiße Farbe ist im Sonderangebot.",
        event_b="Matte Farbe ist im Sonderangebot.",
        prob_texts={
            "pa": "weiße Farbe im Sonderangebot ist",
            "pna": "beige Farbe im Sonderangebot ist",
            "pb": "matte Farbe im Sonderangebot ist",
            "pnb": "glänzende Farbe im Sonderangebot ist",
            "pab": "weiße, matte Farbe im Sonderangebot ist",
            "panb": "weiße, glänzende Farbe im Sonderangebot ist",
            "pnab": "beige, matte Farbe im Sonderangebot ist",
            "pnanb": "beige, glänzende Farbe im Sonderangebot ist",
            "paub": "weiße oder matte Farbe im Sonderangebot ist",
            "paunb": "weiße oder glänzende Farbe im Sonderangebot ist",
            "pnaub": "beige oder matte Farbe im Sonderangebot ist",
            "pnaunb": "beige oder glänzende Farbe im Sonderangebot ist",
            "pba": "weiße Farbe im Sonderangebot matt ist",
            "pnba": "weiße Farbe im Sonderangebot glänzend ist",
            "pbna": "beige Farbe im Sonderangebot matt ist",
            "pnbna": "beige Farbe im Sonderangebot glänzend ist",
            "pab_c": "matte Farbe im Sonderangebot weiß ist",
            "pnab_c": "matte Farbe im Sonderangebot beige ist",
            "panb_c": "glänzende Farbe im Sonderangebot weiß ist",
            "pnanb_c": "glänzende Farbe im Sonderangebot beige ist",
        },
        independence_claim="Ob sich eine weiße oder beige Farbe im Sonderangebot befindet, hat keine Auswirkung darauf, ob die Farbe matt oder glänzend ist.",
        dependence_claim="Ob sich eine weiße oder beige Farbe im Sonderangebot befindet, hat eine Auswirkung darauf, ob die Farbe matt oder glänzend ist.",
    ),
    # 13) Erpressung
    ABScenarioTemplate(
        intro="Personen werden damit erpresst, dass Hacker angeblich Mitschnitte einer Webcam besitzen, die die Person beim Pornokonsum zeigt.",
        event_a="Ein Opfer ist minderjährig.",
        event_b="Ein Opfer alarmiert die Polizei.",
        prob_texts={
            "pa": "ein Opfer minderjährig ist",
            "pna": "ein Opfer erwachsen ist",
            "pb": "ein Opfer die Polizei alarmiert",
            "pnb": "ein Opfer nicht die Polizei alarmiert",
            "pab": "ein Opfer minderjährig ist und die Polizei alarmiert",
            "panb": "ein Opfer minderjährig ist und nicht die Polizei alarmiert",
            "pnab": "ein Opfer erwachsen ist und die Polizei alarmiert",
            "pnanb": "ein Opfer erwachsen ist und nicht die Polizei alarmiert",
            "paub": "ein Opfer minderjährig ist oder die Polizei alarmiert",
            "paunb": "ein Opfer minderjährig ist oder nicht die Polizei alarmiert",
            "pnaub": "ein Opfer erwachsen ist oder die Polizei alarmiert",
            "pnaunb": "ein Opfer erwachsen ist oder nicht die Polizei alarmiert",
            "pba": "ein minderjähriges Opfer die Polizei alarmiert",
            "pnba": "ein minderjähriges Opfer nicht die Polizei alarmiert",
            "pbna": "ein erwachsenes Opfer die Polizei alarmiert",
            "pnbna": "ein erwachsenes Opfer nicht die Polizei alarmiert",
            "pab_c": "ein Opfer, das die Polizei alarmiert, minderjährig ist",
            "pnab_c": "ein Opfer, das die Polizei alarmiert, erwachsen ist",
            "panb_c": "ein Opfer, das die Polizei nicht alarmiert, minderjährig ist",
            "pnanb_c": "ein Opfer, das die Polizei nicht alarmiert, erwachsen ist",
        },
        independence_claim="Das Alter des Opfers hat keine Auswirkung darauf, ob die Polizei alarmiert wird.",
        dependence_claim="Das Alter des Opfers hat eine Auswirkung darauf, ob die Polizei alarmiert wird.",
    ),
    # 14) Glaserei
    ABScenarioTemplate(
        intro="In einer Glaserei können bei der Produktion von hochwertigen Weingläsern zwei Fehler auftreten: Risse und Blaseneinschlüsse.",
        event_a="Ein Glas hat einen Riss.",
        event_b="Ein Glas hat einen Blaseneinschluss.",
        prob_texts={
            "pa": "ein Glas einen Riss hat",
            "pna": "ein Glas keinen Riss hat",
            "pb": "ein Glas einen Blaseneinschluss hat",
            "pnb": "ein Glas keinen Blaseneinschluss hat",
            "pab": "ein Glas beide Fehler aufweist",
            "panb": "ein Glas einen Riss aber keinen Blaseneinschluss hat",
            "pnab": "ein Glas keinen Riss aber einen Blaseneinschluss hat",
            "pnanb": "ein Glas keinen Fehler aufweist",
            "paub": "ein Glas mindestens einen Fehler aufweist",
            "paunb": "ein Glas einen Riss oder keinen Blaseneinschluss hat",
            "pnaub": "ein Glas keinen Riss oder einen Blaseneinschluss hat",
            "pnaunb": "ein Glas zumindest einen Fehler nicht aufweist",
            "pba": "ein Glas mit Riss einen Blaseneinschluss hat",
            "pnba": "ein Glas mit Riss keinen Blaseneinschluss hat",
            "pbna": "ein Glas ohne Riss einen Blaseneinschluss hat",
            "pnbna": "ein Glas ohne Riss keinen Blaseneinschluss hat",
            "pab_c": "ein Glas mit Blaseneinschluss einen Riss hat",
            "pnab_c": "ein Glas mit Blaseneinschluss keinen Riss hat",
            "panb_c": "ein Glas ohne Blaseneinschluss einen Riss hat",
            "pnanb_c": "ein Glas ohne Blaseneinschluss keinen Riss hat",
        },
        independence_claim="Die beiden Fehler hängen nicht voneinander ab.",
        dependence_claim="Die beiden Fehler hängen voneinander ab.",
    ),
    # 15) Partnerbörse
    ABScenarioTemplate(
        intro="Amalia sucht auf einer Online-Partnerbörse den Mann fürs Leben. Neben der äußerlichen Attraktivität ist es für sie wichtig, dass ihr Partner nicht raucht.",
        event_a="Ein vorgeschlagener Partner ist attraktiv.",
        event_b="Ein vorgeschlagener Partner raucht.",
        prob_texts={
            "pa": "ein vorgeschlagener Partner attraktiv ist",
            "pna": "ein vorgeschlagener Partner unattraktiv ist",
            "pb": "ein vorgeschlagener Partner raucht",
            "pnb": "ein vorgeschlagener Partner nicht raucht",
            "pab": "ein vorgeschlagener Partner ein attraktiver Raucher ist",
            "panb": "ein vorgeschlagener Partner ein attraktiver Nichtraucher ist",
            "pnab": "ein vorgeschlagener Partner ein unattraktiver Raucher ist",
            "pnanb": "ein vorgeschlagener Partner ein unattraktiver Nichtraucher ist",
            "paub": "ein vorgeschlagener Partner attraktiv ist oder raucht",
            "paunb": "ein vorgeschlagener Partner attraktiv ist oder nicht raucht",
            "pnaub": "ein vorgeschlagener Partner unattraktiv ist oder raucht",
            "pnaunb": "ein vorgeschlagener Partner unattraktiv ist oder nicht raucht",
            "pba": "ein vorgeschlagener, attraktiver Partner raucht",
            "pnba": "ein vorgeschlagener, attraktiver Partner nicht raucht",
            "pbna": "ein vorgeschlagener, unattraktiver Partner raucht",
            "pnbna": "ein vorgeschlagener, unattraktiver Partner nicht raucht",
            "pab_c": "ein vorgeschlagener Raucher attraktiv ist",
            "pnab_c": "ein vorgeschlagener Raucher unattraktiv ist",
            "panb_c": "ein vorgeschlagener Nichtraucher attraktiv ist",
            "pnanb_c": "ein vorgeschlagener Nichtraucher unattraktiv ist",
        },
        independence_claim="Es gibt keinen Zusammenhang zwischen der Attraktivität eines vorgeschlagenen Partners und seinem Rauchverhalten.",
        dependence_claim="Es gibt einen Zusammenhang zwischen der Attraktivität eines vorgeschlagenen Partners und seinem Rauchverhalten.",
    ),
    # 16) Smartwatches
    ABScenarioTemplate(
        intro="Ein Unternehmen produziert Smartwatches, die vor dem Verkauf durch ein automatisiertes Verfahren ausgiebig getestet werden. Fehlerhafte Smartwatches werden aussortiert, allerdings kommt es auch zu Fehlentscheidungen.",
        event_a="Eine Smartwatch ist fehlerfrei.",
        event_b="Eine Smartwatch wird aussortiert.",
        prob_texts={
            "pa": "eine Smartwatch fehlerfrei ist",
            "pna": "eine Smartwatch fehlerbehaftet ist",
            "pb": "eine Smartwatch aussortiert wird",
            "pnb": "eine Smartwatch nicht aussortiert wird",
            "pab": "eine Smartwatch fehlerfrei ist und aussortiert wird",
            "panb": "eine Smartwatch fehlerfrei ist und nicht aussortiert wird",
            "pnab": "eine Smartwatch fehlerbehaftet ist und aussortiert wird",
            "pnanb": "eine Smartwatch fehlerbehaftet ist und nicht aussortiert wird",
            "paub": "eine Smartwatch fehlerfrei ist oder aussortiert wird",
            "paunb": "eine Smartwatch fehlerfrei ist oder nicht aussortiert wird",
            "pnaub": "eine Smartwatch fehlerbehaftet ist oder aussortiert wird",
            "pnaunb": "eine Smartwatch fehlerbehaftet ist oder nicht aussortiert wird",
            "pba": "eine fehlerfreie Smartwatch aussortiert wird",
            "pnba": "eine fehlerfreie Smartwatch nicht aussortiert wird",
            "pbna": "eine fehlerbehaftete Smartwatch aussortiert wird",
            "pnbna": "eine fehlerbehaftete Smartwatch nicht aussortiert wird",
            "pab_c": "eine aussortierte Smartwatch fehlerfrei ist",
            "pnab_c": "eine aussortierte Smartwatch fehlerbehaftet ist",
            "panb_c": "eine nicht aussortierte Smartwatch fehlerfrei ist",
            "pnanb_c": "eine nicht aussortierte Smartwatch fehlerbehaftet ist",
        },
        independence_claim="Das automatisierte Testverfahren ist überflüssig.",
        dependence_claim="Fehlerbehaftete Smartwatches werden mit einer anderen Wahrscheinlichkeit als fehlerfreie Smartwatches aussortiert.",
    ),
    # 17) Pommes
    ABScenarioTemplate(
        intro="Der Besitzer einer Imbissbude interessiert sich dafür, in welchen Größen Pommes bestellt werden und ob Ketchup oder Mayonnaise gewünscht wird.",
        event_a="Es wird eine große Pommes bestellt.",
        event_b="Es wird eine Pommes mit Ketchup bestellt.",
        prob_texts={
            "pa": "eine große Pommes bestellt wird",
            "pna": "eine kleine Pommes bestellt wird",
            "pb": "eine Pommes mit Ketchup bestellt wird",
            "pnb": "eine Pommes mit Mayonnaise bestellt wird",
            "pab": "eine große Pommes mit Ketchup bestellt wird",
            "panb": "eine große Pommes mit Mayonnaise bestellt wird",
            "pnab": "eine kleine Pommes mit Ketchup bestellt wird",
            "pnanb": "eine kleine Pommes mit Mayonnaise bestellt wird",
            "paub": "eine große Pommes oder eine Pommes mit Ketchup bestellt wird",
            "paunb": "eine große Pommes oder eine Pommes mit Mayonnaise bestellt wird",
            "pnaub": "eine kleine Pommes oder eine Pommes mit Ketchup bestellt wird",
            "pnaunb": "eine kleine Pommes oder eine Pommes mit Mayonnaise bestellt wird",
            "pba": "die Bestellung einer großen Pommes mit Ketchup ist",
            "pnba": "die Bestellung einer großen Pommes mit Mayonnaise ist",
            "pbna": "die Bestellung einer kleinen Pommes mit Ketchup ist",
            "pnbna": "die Bestellung einer kleinen Pommes mit Mayonnaise ist",
            "pab_c": "die Bestellung einer Pommes mit Ketchup eine große Pommes ist",
            "pnab_c": "die Bestellung einer Pommes mit Ketchup eine kleine Pommes ist",
            "panb_c": "die Bestellung einer Pommes mit Mayonnaise eine große Pommes ist",
            "pnanb_c": "die Bestellung einer Pommes mit Mayonnaise eine kleine Pommes ist",
        },
        independence_claim="Es gibt keinen Zusammenhang zwischen der Größe einer bestellten Pommes und dem gewünschten Dressing.",
        dependence_claim="Es gibt einen Zusammenhang zwischen der Größe einer bestellten Pommes und dem gewünschten Dressing.",
    ),
    # 18) Beamer
    ABScenarioTemplate(
        intro="Ein Unternehmen verkauft neue und gebrauchte Beamer.",
        event_a="Ein Kunde kauft Neuware.",
        event_b="Ein Kunde reklamiert das Produkt.",
        prob_texts={
            "pa": "ein Kunde Neuware kauft",
            "pna": "ein Kunde Gebrauchtware kauft",
            "pb": "ein Kunde ein Produkt reklamiert",
            "pnb": "ein Kunde ein Produkt nicht reklamiert",
            "pab": "ein Kunde Neuware kauft und diese reklamiert",
            "panb": "ein Kunde Neuware kauft und diese nicht reklamiert",
            "pnab": "ein Kunde Gebrauchtware kauft und diese reklamiert",
            "pnanb": "ein Kunde Gebrauchtware kauft und diese nicht reklamiert",
            "paub": "ein Kunde Neuware kauft oder die Ware reklamiert",
            "paunb": "ein Kunde Neuware kauft oder die Ware nicht reklamiert",
            "pnaub": "ein Kunde Gebrauchtware kauft oder die Ware reklamiert",
            "pnaunb": "ein Kunde Gebrauchtware kauft oder die Ware nicht reklamiert",
            "pba": "ein Kunde Neuware reklamiert",
            "pnba": "ein Kunde Neuware nicht reklamiert",
            "pbna": "ein Kunde Gebrauchtware reklamiert",
            "pnbna": "ein Kunde Gebrauchtware nicht reklamiert",
            "pab_c": "eine reklamierte Ware neu ist",
            "pnab_c": "eine reklamierte Ware gebraucht ist",
            "panb_c": "eine nicht reklamierte Ware neu ist",
            "pnanb_c": "eine nicht reklamierte Ware gebraucht ist",
        },
        independence_claim="Ob ein Produkt Neu- oder Gebrauchtware ist, hat keinen Einfluss darauf, ob es reklamiert wird.",
        dependence_claim="Ob ein Produkt Neu- oder Gebrauchtware ist, hat einen Einfluss darauf, ob es reklamiert wird.",
    ),
    # 19) Lippenstifte
    ABScenarioTemplate(
        intro="Eine Influencerin stellt ihren Followern zwei neue Lippenstifte vor: Ambition und Bonny. Sie möchte wissen, wie die beiden Lippenstifte ankommen.",
        event_a="Einem Follower gefällt Ambition.",
        event_b="Einem Follower gefällt Bonny.",
        prob_texts={
            "pa": "einem Follower Ambition gefällt",
            "pna": "einem Follower Ambition nicht gefällt",
            "pb": "einem Follower Bonny gefällt",
            "pnb": "einem Follower Bonny nicht gefällt",
            "pab": "einem Follower beide Lippenstifte gefallen",
            "panb": "einem Follower Ambition gefällt, Bonny aber nicht",
            "pnab": "einem Follower Bonny gefällt, Ambition aber nicht",
            "pnanb": "einem Follower keiner der Lippenstifte gefällt",
            "paub": "einem Follower mindestens einer der beiden Lippenstifte gefällt",
            "paunb": "einem Follower Ambition gefällt oder Bonny nicht gefällt",
            "pnaub": "einem Follower Ambition nicht gefällt oder Bonny gefällt",
            "pnaunb": "einem Follower mindestens einer der beiden Lippenstifte nicht gefällt",
            "pba": "einem Follower, dem Ambition gefällt, auch Bonny gefällt",
            "pnba": "einem Follower, dem Ambition gefällt, Bonny nicht gefällt",
            "pbna": "einem Follower, dem Ambition nicht gefällt, Bonny gefällt",
            "pnbna": "einem Follower, dem Ambition nicht gefällt, auch Bonny nicht gefällt",
            "pab_c": "einem Follower, dem Bonny gefällt, auch Ambition gefällt",
            "pnab_c": "einem Follower, dem Bonny gefällt, Ambition nicht gefällt",
            "panb_c": "einem Follower, dem Bonny nicht gefällt, Ambition gefällt",
            "pnanb_c": "einem Follower, dem Bonny nicht gefällt, auch Ambition nicht gefällt",
        },
        independence_claim="Die Bewertung der beiden Lippenstifte durch einen Follower ist stochastisch unabhängig.",
        dependence_claim="Die Bewertung der beiden Lippenstifte durch einen Follower ist stochastisch abhängig.",
    ),
    # 20) Lebensmittelkonzern
    ABScenarioTemplate(
        intro="Ein Lebensmittelkonzern verschafft sich einen Überblick darüber, welche seiner Produkte biologisch und regional sind.",
        event_a="Ein Produkt ist biologisch.",
        event_b="Ein Produkt ist regional.",
        prob_texts={
            "pa": "ein Produkt biologisch ist",
            "pna": "ein Produkt nicht biologisch ist",
            "pb": "ein Produkt regional ist",
            "pnb": "ein Produkt nicht aus der Region stammt",
            "pab": "ein Produkt biologisch und regional ist",
            "panb": "ein Produkt biologisch ist aber nicht aus der Region stammt",
            "pnab": "ein Produkt nicht biologisch ist aber aus der Region stammt",
            "pnanb": "ein Produkt nicht biologisch und nicht regional ist",
            "paub": "ein Produkt biologisch oder regional ist",
            "paunb": "ein Produkt biologisch oder nicht regional ist",
            "pnaub": "ein Produkt nicht biologisch oder regional ist",
            "pnaunb": "ein Produkt nicht biologisch oder nicht regional ist",
            "pba": "ein Bioprodukt aus der Region stammt",
            "pnba": "ein Bioprodukt nicht aus der Region stammt",
            "pbna": "ein Produkt, das nicht biologisch ist, aus der Region stammt",
            "pnbna": "ein Produkt, das nicht biologisch ist, nicht aus der Region stammt",
            "pab_c": "ein regionales Produkt biologisch ist",
            "pnab_c": "ein regionales Produkt nicht biologisch ist",
            "panb_c": "ein Produkt, das nicht aus der Region stammt, biologisch ist",
            "pnanb_c": "ein Produkt, das nicht aus der Region stammt, nicht biologisch ist",
        },
        independence_claim="Ob ein Produkt biologisch ist, hat keinen Einfluss darauf, ob es regional ist.",
        dependence_claim="Ob ein Produkt biologisch ist, hat einen Einfluss darauf, ob es regional ist.",
    ),
]
