from dataclasses import dataclass, field


@dataclass(frozen=True)
class ABScenarioTemplate:
    intro: str
    event_a: str
    event_b: str
    # Textbausteine für "die Wahrscheinlichkeit, dass ..."
    # Werden in Check 4 (Ablesen/Berechnen) genutzt.
    prob_texts: dict[str, str] = field(default_factory=dict)
    # Schlüssel: pa, pna, pb, pnb,
    #            pab, panb, pnab, pnanb,
    #            paub, paunb, pnaub, pnaunb


SCENARIOS: list[ABScenarioTemplate] = [
    # 1) Halbleiter
    ABScenarioTemplate(
        intro="Ein Hersteller von Halbleitern erhält Aufträge von Groß- und Kleinkunden. Alle Kunden können zwischen Basis- und Premium-Qualität wählen.",
        event_a="Ein Großkunde bestellt Halbleiter.",
        event_b="Halbleiter werden in Premium-Qualität bestellt.",
        prob_texts={
            "pa": "ein Großkunde Halbleiter bestellt",
            "pna": "ein Kleinkunde Halbleiter bestellt",
            "pb": "Halbleiter in Premium-Qualität bestellt werden",
            "pnb": "Halbleiter in Basis-Qualität bestellt werden",
            "pab": "eine Bestellung von einem Großkunden stammt und Premium-Qualität erfordert",
            "panb": "eine Bestellung von einem Großkunden stammt und Basis-Qualität erfordert",
            "pnab": "eine Bestellung von einem Kleinkunden stammt und Premium-Qualität erfordert",
            "pnanb": "eine Bestellung von einem Kleinkunden stammt und Basis-Qualität erfordert",
            "paub": "ein Großkunde Halbleiter bestellt oder Halbleiter in Premium-Qualität bestellt werden",
            "paunb": "ein Großkunde Halbleiter bestellt oder Halbleiter in Basis-Qualität bestellt werden",
            "pnaub": "ein Kleinkunde Halbleiter bestellt oder Halbleiter in Premium-Qualität bestellt werden",
            "pnaunb": "ein Kleinkunde Halbleiter bestellt oder Halbleiter in Basis-Qualität bestellt werden",
        },
    ),
    # 2) Zugbegleiterin
    ABScenarioTemplate(
        intro="Eine Zugbegleiterin kontrolliert die Fahrscheine und das Einhalten der Maskenpflicht in einem ICE von Hamburg nach München.",
        event_a="Ein Passagier hat einen gültigen Fahrschein.",
        event_b="Ein Passagier trägt eine Maske.",
        prob_texts={
            "pa": "ein Passagier einen gültigen Fahrschein hat",
            "pna": "ein Passagier keinen gültigen Fahrschein hat",
            "pb": "ein Passagier eine Maske trägt",
            "pnb": "ein Passagier keine Maske trägt",
            "pab": "ein Passagier einen gültigen Fahrschein hat und eine Maske trägt",
            "panb": "ein Passagier einen gültigen Fahrschein hat und keine Maske trägt",
            "pnab": "ein Passagier keinen gültigen Fahrschein hat und eine Maske trägt",
            "pnanb": "ein Passagier keinen gültigen Fahrschein hat und keine Maske trägt",
            "paub": "ein Passagier einen gültigen Fahrschein hat oder eine Maske trägt",
            "paunb": "ein Passagier einen gültigen Fahrschein hat oder keine Maske trägt",
            "pnaub": "ein Passagier keinen gültigen Fahrschein hat oder eine Maske trägt",
            "pnaunb": "ein Passagier keinen gültigen Fahrschein hat oder keine Maske trägt",
        },
    ),
    # 3) Eisstand
    ABScenarioTemplate(
        intro="Ein Eisstand bietet Getränke an: Schokolade und Kaffee, jeweils entweder heiß oder kalt zubereitet.",
        event_a="Ein Kunde bestellt eine Schokolade.",
        event_b="Ein Kunde bestellt ein heißes Getränk.",
        prob_texts={
            "pa": "ein Kunde eine Schokolade bestellt",
            "pna": "ein Kunde einen Kaffee bestellt",
            "pb": "ein Kunde ein heißes Getränk bestellt",
            "pnb": "ein Kunde ein kaltes Getränk bestellt",
            "pab": "ein Kunde eine heiße Schokolade bestellt",
            "panb": "ein Kunde eine Eisschokolade bestellt",
            "pnab": "ein Kunde einen heißen Kaffee bestellt",
            "pnanb": "ein Kunde einen Eiskaffee bestellt",
            "paub": "ein Kunde eine Schokolade oder ein heißes Getränk bestellt",
            "paunb": "ein Kunde eine Schokolade oder ein kaltes Getränk bestellt",
            "pnaub": "ein Kunde einen Kaffee oder ein heißes Getränk bestellt",
            "pnaunb": "ein Kunde einen Kaffee oder ein kaltes Getränk bestellt",
        },
    ),
    # 4) Würfel
    ABScenarioTemplate(
        intro="Ein angeblich verzauberter Würfel wird geworfen. Bevor man wirft, kann man einen Zauberspruch aufsagen.",
        event_a="Es wird eine Sechs geworfen.",
        event_b="Es wird ein Zauberspruch aufgesagt.",
        prob_texts={
            "pa": "eine Sechs geworfen wird",
            "pna": "keine Sechs geworfen wird",
            "pb": "ein Zauberspruch aufgesagt wird",
            "pnb": "kein Zauberspruch aufgesagt wird",
            "pab": "eine Sechs geworfen und ein Zauberspruch aufgesagt wird",
            "panb": "eine Sechs geworfen und kein Zauberspruch aufgesagt wird",
            "pnab": "keine Sechs geworfen und ein Zauberspruch aufgesagt wird",
            "pnanb": "keine Sechs geworfen und kein Zauberspruch aufgesagt wird",
            "paub": "eine Sechs geworfen oder ein Zauberspruch aufgesagt wird",
            "paunb": "eine Sechs geworfen oder kein Zauberspruch aufgesagt wird",
            "pnaub": "keine Sechs geworfen oder ein Zauberspruch aufgesagt wird",
            "pnaunb": "keine Sechs geworfen oder kein Zauberspruch aufgesagt wird",
        },
    ),
    # 5) Bundesbank
    ABScenarioTemplate(
        intro="Für das Controlling bei der Deutschen Bundesbank bewerben sich Mathematiker und Wirtschaftswissenschaftler mit Bachelor- oder Masterabschluss.",
        event_a="Ein Bewerber ist Mathematiker.",
        event_b="Ein Bewerber hat einen Bachelor.",
        prob_texts={
            "pa": "ein Bewerber Mathematiker ist",
            "pna": "ein Bewerber Wirtschaftswissenschaftler ist",
            "pb": "ein Bewerber einen Bachelor hat",
            "pnb": "ein Bewerber einen Master hat",
            "pab": "ein Bewerber einen Bachelor in Mathematik hat",
            "panb": "ein Bewerber einen Master in Mathematik hat",
            "pnab": "ein Bewerber einen Bachelor in Wirtschaftswissenschaft hat",
            "pnanb": "ein Bewerber einen Master in Wirtschaftswissenschaften hat",
            "paub": "ein Bewerber Mathematiker ist oder einen Bachelor hat",
            "paunb": "ein Bewerber Mathematiker ist oder einen Master hat",
            "pnaub": "ein Bewerber Wirtschaftswissenschaftler ist oder einen Bachelor hat",
            "pnaunb": "ein Bewerber Wirtschaftswissenschaftler ist oder einen Master hat",
        },
    ),
    # 6) Führerscheinprüfung
    ABScenarioTemplate(
        intro="Bei der praktischen Führerscheinprüfung wird untersucht, ob der Gemütszustand des Prüfers das Ergebnis beeinflusst.",
        event_a="Der Prüfling besteht.",
        event_b="Der Prüfer ist ausgeschlafen.",
        prob_texts={
            "pa": "ein Prüfling besteht",
            "pna": "ein Prüfling durchfällt",
            "pb": "ein Prüfer ausgeschlafen ist",
            "pnb": "ein Prüfer nicht ausgeschlafen ist",
            "pab": "ein Prüfling besteht und ein Prüfer ausgeschlafen ist",
            "panb": "ein Prüfling besteht und ein Prüfer nicht ausgeschlafen ist",
            "pnab": "ein Prüfling durchfällt und ein Prüfer ausgeschlafen ist",
            "pnanb": "ein Prüfling durchfällt und ein Prüfer nicht ausgeschlafen ist",
            "paub": "ein Prüfling besteht oder ein Prüfer ausgeschlafen ist",
            "paunb": "ein Prüfling besteht oder ein Prüfer nicht ausgeschlafen ist",
            "pnaub": "ein Prüfling durchfällt oder ein Prüfer ausgeschlafen ist",
            "pnaunb": "ein Prüfling durchfällt oder ein Prüfer nicht ausgeschlafen ist",
        },
    ),
    # 7) Hanteln
    ABScenarioTemplate(
        intro="In einem Sportgeschäft werden Hanteln aus Metall und Kunststoff angeboten. Zur Schonung der Handgelenke sind einige Hanteln zudem mit einem drehbaren Griff ausgestattet.",
        event_a="Eine Hantel ist aus Metall.",
        event_b="Eine Hantel hat einen drehbaren Griff.",
        prob_texts={
            "pa": "eine Hantel aus Metall ist",
            "pna": "eine Hantel aus Kunststoff ist",
            "pb": "eine Hantel einen drehbaren Griff hat",
            "pnb": "eine Hantel keinen drehbaren Griff hat",
            "pab": "eine Hantel aus Metall ist und einen drehbaren Griff hat",
            "panb": "eine Hantel aus Metall ist und keinen drehbaren Griff hat",
            "pnab": "eine Hantel aus Kunststoff ist und einen drehbaren Griff hat",
            "pnanb": "eine Hantel aus Kunststoff ist und keinen drehbaren Griff hat",
            "paub": "eine Hantel aus Metall ist oder einen drehbaren Griff hat",
            "paunb": "eine Hantel aus Metall ist oder keinen drehbaren Griff hat",
            "pnaub": "eine Hantel aus Kunststoff ist oder einen drehbaren Griff hat",
            "pnaunb": "eine Hantel aus Kunststoff ist oder keinen drehbaren Griff hat",
        },
    ),
    # 8) Fußballspielerin
    ABScenarioTemplate(
        intro="Eine Fußballspielerin nimmt vor einigen Spielen Doping ein. Spiele können entweder gewonnen oder verloren werden.",
        event_a="Sie gewinnt ein Spiel.",
        event_b="Sie dopt in einem Spiel.",
        prob_texts={
            "pa": "sie ein Spiel gewinnt",
            "pna": "sie ein Spiel verliert",
            "pb": "sie in einem Spiel dopt",
            "pnb": "sie in einem Spiel nicht dopt",
            "pab": "sie ein Spiel gewinnt und dopt",
            "panb": "sie ein Spiel gewinnt und nicht dopt",
            "pnab": "sie ein Spiel verliert und dopt",
            "pnanb": "sie ein Spiel verliert und nicht dopt",
            "paub": "sie ein Spiel gewinnt oder dopt",
            "paunb": "sie ein Spiel gewinnt oder nicht dopt",
            "pnaub": "sie ein Spiel verliert oder dopt",
            "pnaunb": "sie ein Spiel verliert oder nicht dopt",
        },
    ),
    # 9) Home-Office
    ABScenarioTemplate(
        intro="Ein Unternehmen stellt fest, ob seine Mitarbeiter im Home-Office oder in Präsenz arbeiten. Es gibt Voll- und Teilzeitkräfte.",
        event_a="Ein Mitarbeiter arbeitet im Home-Office.",
        event_b="Ein Mitarbeiter arbeitet in Vollzeit.",
        prob_texts={
            "pa": "ein Mitarbeiter im Home-Office arbeitet",
            "pna": "ein Mitarbeiter in Präsenz arbeitet",
            "pb": "ein Mitarbeiter in Vollzeit arbeitet",
            "pnb": "ein Mitarbeiter in Teilzeit arbeitet",
            "pab": "ein Mitarbeiter in Vollzeit und im Home-Office arbeitet",
            "panb": "ein Mitarbeiter in Teilzeit und im Home-Office arbeitet",
            "pnab": "ein Mitarbeiter in Vollzeit und in Präsenz arbeitet",
            "pnanb": "ein Mitarbeiter in Teilzeit und in Präsenz arbeitet",
            "paub": "ein Mitarbeiter im Home-Office oder in Vollzeit arbeitet",
            "paunb": "ein Mitarbeiter im Home-Office oder in Teilzeit arbeitet",
            "pnaub": "ein Mitarbeiter in Präsenz oder in Vollzeit arbeitet",
            "pnaunb": "ein Mitarbeiter in Präsenz oder in Teilzeit arbeitet",
        },
    ),
    # 10) Restaurants
    ABScenarioTemplate(
        intro="Die Geschäftsleitung eines Restaurants interessiert sich dafür, wie kinderfreundlich die konkurrierenden Restaurants der Stadt sind.",
        event_a="Ein Restaurant hat einen Biergarten.",
        event_b="Ein Restaurant hat eine Spielecke.",
        prob_texts={
            "pa": "ein Restaurant über einen Biergarten verfügt",
            "pna": "ein Restaurant über keinen Biergarten verfügt",
            "pb": "ein Restaurant über eine Spielecke verfügt",
            "pnb": "ein Restaurant über keine Spielecke verfügt",
            "pab": "ein Restaurant über einen Biergarten und eine Spielecke verfügt",
            "panb": "ein Restaurant über einen Biergarten aber über keine Spielecke verfügt",
            "pnab": "ein Restaurant über keinen Biergarten aber über eine Spielecke verfügt",
            "pnanb": "ein Restaurant weder über einen Biergarten noch über eine Spielecke verfügt",
            "paub": "ein Restaurant über einen Biergarten oder eine Spielecke verfügt",
            "paunb": "ein Restaurant über einen Biergarten oder über keine Spielecke verfügt",
            "pnaub": "ein Restaurant über keinen Biergarten oder über eine Spielecke verfügt",
            "pnaunb": "ein Restaurant über keinen Biergarten oder über keine Spielecke verfügt",
        },
    ),
    # 11) Holzkohle
    ABScenarioTemplate(
        intro="In einem Gartencenter wird konventionelle und nachhaltige Holzkohle angeboten. Beide Kohlearten sind als teure Originalprodukte oder günstige Nachahmerprodukte erhältlich.",
        event_a="Ein Kunde kauft nachhaltige Holzkohle.",
        event_b="Ein Kunde kauft ein Originalprodukt.",
        prob_texts={
            "pa": "ein Kunde nachhaltige Holzkohle kauft",
            "pna": "ein Kunde konventionelle Holzkohle kauft",
            "pb": "ein Kunde ein Originalprodukt kauft",
            "pnb": "ein Kunde ein Nachahmerprodukt kauft",
            "pab": "ein Kunde ein nachhaltiges Originalprodukt kauft",
            "panb": "ein Kunde ein nachhaltiges Nachahmerprodukt kauft",
            "pnab": "ein Kunde ein konventionelles Originalprodukt kauft",
            "pnanb": "ein Kunde ein konventionelles Nachahmerprodukt kauft",
            "paub": "ein Kunde nachhaltige Holzkohle oder ein Originalprodukt kauft",
            "paunb": "ein Kunde nachhaltige Holzkohle oder ein Nachahmerprodukt kauft",
            "pnaub": "ein Kunde konventionelle Holzkohle oder ein Originalprodukt kauft",
            "pnaunb": "ein Kunde konventionelle Holzkohle oder ein Nachahmerprodukt kauft",
        },
    ),
    # 12) Wandfarbe
    ABScenarioTemplate(
        intro="Ein Geschäft für Heimwerkerbedarf bietet Wandfarbe in den Farben weiß und beige an, jeweils entweder matt oder glänzend. Genau ein Produkt ist im Sonderangebot.",
        event_a="Weiße Farbe ist im Sonderangebot.",
        event_b="Matte Farbe ist im Sonderangebot.",
        prob_texts={
            "pa": "weiße Farbe im Sonderangebot ist",
            "pna": "beige Farbe im Sonderangebot ist",
            "pb": "matte Farbe im Sonderangebot ist",
            "pnb": "glänzende Farbe im Sonderangebot ist",
            "pab": "weiße, matte Farbe im Sonderangebot ist",
            "panb": "weiße, glänzende Farbe im Sonderangebot ist",
            "pnab": "beige, matte Farbe im Sonderangebot ist",
            "pnanb": "beige, glänzende Farbe im Sonderangebot ist",
            "paub": "weiße oder matte Farbe im Sonderangebot ist",
            "paunb": "weiße oder glänzende Farbe im Sonderangebot ist",
            "pnaub": "beige oder matte Farbe im Sonderangebot ist",
            "pnaunb": "beige oder glänzende Farbe im Sonderangebot ist",
        },
    ),
    # 13) Erpressung
    ABScenarioTemplate(
        intro="Personen werden damit erpresst, dass Hacker angeblich Mitschnitte einer Webcam besitzen, die die Person beim Pornokonsum zeigt.",
        event_a="Ein Opfer ist minderjährig.",
        event_b="Ein Opfer alarmiert die Polizei.",
        prob_texts={
            "pa": "ein Opfer minderjährig ist",
            "pna": "ein Opfer erwachsen ist",
            "pb": "ein Opfer die Polizei alarmiert",
            "pnb": "ein Opfer nicht die Polizei alarmiert",
            "pab": "ein Opfer minderjährig ist und die Polizei alarmiert",
            "panb": "ein Opfer minderjährig ist und nicht die Polizei alarmiert",
            "pnab": "ein Opfer erwachsen ist und die Polizei alarmiert",
            "pnanb": "ein Opfer erwachsen ist und nicht die Polizei alarmiert",
            "paub": "ein Opfer minderjährig ist oder die Polizei alarmiert",
            "paunb": "ein Opfer minderjährig ist oder nicht die Polizei alarmiert",
            "pnaub": "ein Opfer erwachsen ist oder die Polizei alarmiert",
            "pnaunb": "ein Opfer erwachsen ist oder nicht die Polizei alarmiert",
        },
    ),
    # 14) Glaserei
    ABScenarioTemplate(
        intro="In einer Glaserei können bei der Produktion von hochwertigen Weingläsern zwei Fehler auftreten: Risse und Blaseneinschlüsse.",
        event_a="Ein Glas hat einen Riss.",
        event_b="Ein Glas hat einen Blaseneinschluss.",
        prob_texts={
            "pa": "ein Glas einen Riss hat",
            "pna": "ein Glas keinen Riss hat",
            "pb": "ein Glas einen Blaseneinschluss hat",
            "pnb": "ein Glas keinen Blaseneinschluss hat",
            "pab": "ein Glas beide Fehler aufweist",
            "panb": "ein Glas einen Riss aber keinen Blaseneinschluss hat",
            "pnab": "ein Glas keinen Riss aber einen Blaseneinschluss hat",
            "pnanb": "ein Glas keinen Fehler aufweist",
            "paub": "ein Glas mindestens einen Fehler aufweist",
            "paunb": "ein Glas einen Riss oder keinen Blaseneinschluss hat",
            "pnaub": "ein Glas keinen Riss oder einen Blaseneinschluss hat",
            "pnaunb": "ein Glas zumindest einen Fehler nicht aufweist",
        },
    ),
    # 15) Partnerbörse
    ABScenarioTemplate(
        intro="Amalia sucht auf einer Online-Partnerbörse den Mann fürs Leben. Neben der äußerlichen Attraktivität ist es für sie wichtig, dass ihr Partner nicht raucht.",
        event_a="Ein vorgeschlagener Partner ist attraktiv.",
        event_b="Ein vorgeschlagener Partner raucht.",
        prob_texts={
            "pa": "ein vorgeschlagener Partner attraktiv ist",
            "pna": "ein vorgeschlagener Partner unattraktiv ist",
            "pb": "ein vorgeschlagener Partner raucht",
            "pnb": "ein vorgeschlagener Partner nicht raucht",
            "pab": "ein vorgeschlagener Partner ein attraktiver Raucher ist",
            "panb": "ein vorgeschlagener Partner ein attraktiver Nichtraucher ist",
            "pnab": "ein vorgeschlagener Partner ein unattraktiver Raucher ist",
            "pnanb": "ein vorgeschlagener Partner ein unattraktiver Nichtraucher ist",
            "paub": "ein vorgeschlagener Partner attraktiv ist oder raucht",
            "paunb": "ein vorgeschlagener Partner attraktiv ist oder nicht raucht",
            "pnaub": "ein vorgeschlagener Partner unattraktiv ist oder raucht",
            "pnaunb": "ein vorgeschlagener Partner unattraktiv ist oder nicht raucht",
        },
    ),
    # 16) Smartwatches
    ABScenarioTemplate(
        intro="Ein Unternehmen produziert Smartwatches, die vor dem Verkauf durch ein automatisiertes Verfahren ausgiebig getestet werden. Fehlerhafte Smartwatches werden aussortiert, allerdings kommt es auch zu Fehlentscheidungen.",
        event_a="Eine Smartwatch ist fehlerfrei.",
        event_b="Eine Smartwatch wird aussortiert.",
        prob_texts={
            "pa": "eine Smartwatch fehlerfrei ist",
            "pna": "eine Smartwatch fehlerbehaftet ist",
            "pb": "eine Smartwatch aussortiert wird",
            "pnb": "eine Smartwatch nicht aussortiert wird",
            "pab": "eine Smartwatch fehlerfrei ist und aussortiert wird",
            "panb": "eine Smartwatch fehlerfrei ist und nicht aussortiert wird",
            "pnab": "eine Smartwatch fehlerbehaftet ist und aussortiert wird",
            "pnanb": "eine Smartwatch fehlerbehaftet ist und nicht aussortiert wird",
            "paub": "eine Smartwatch fehlerfrei ist oder aussortiert wird",
            "paunb": "eine Smartwatch fehlerfrei ist oder nicht aussortiert wird",
            "pnaub": "eine Smartwatch fehlerbehaftet ist oder aussortiert wird",
            "pnaunb": "eine Smartwatch fehlerbehaftet ist oder nicht aussortiert wird",
        },
    ),
    # 17) Pommes
    ABScenarioTemplate(
        intro="Der Besitzer einer Imbissbude interessiert sich dafür, in welchen Größen Pommes bestellt werden und ob Ketchup oder Mayonnaise gewünscht wird.",
        event_a="Es wird eine große Pommes bestellt.",
        event_b="Es wird eine Pommes mit Ketchup bestellt.",
        prob_texts={
            "pa": "eine große Pommes bestellt wird",
            "pna": "eine kleine Pommes bestellt wird",
            "pb": "eine Pommes mit Ketchup bestellt wird",
            "pnb": "eine Pommes mit Mayonnaise bestellt wird",
            "pab": "eine große Pommes mit Ketchup bestellt wird",
            "panb": "eine große Pommes mit Mayonnaise bestellt wird",
            "pnab": "eine kleine Pommes mit Ketchup bestellt wird",
            "pnanb": "eine kleine Pommes mit Mayonnaise bestellt wird",
            "paub": "eine große Pommes oder eine Pommes mit Ketchup bestellt wird",
            "paunb": "eine große Pommes oder eine Pommes mit Mayonnaise bestellt wird",
            "pnaub": "eine kleine Pommes oder eine Pommes mit Ketchup bestellt wird",
            "pnaunb": "eine kleine Pommes oder eine Pommes mit Mayonnaise bestellt wird",
        },
    ),
    # 18) Beamer
    ABScenarioTemplate(
        intro="Ein Unternehmen verkauft neue und gebrauchte Beamer.",
        event_a="Ein Kunde kauft Neuware.",
        event_b="Ein Kunde reklamiert das Produkt.",
        prob_texts={
            "pa": "ein Kunde Neuware kauft",
            "pna": "ein Kunde Gebrauchtware kauft",
            "pb": "ein Kunde ein Produkt reklamiert",
            "pnb": "ein Kunde ein Produkt nicht reklamiert",
            "pab": "ein Kunde Neuware kauft und diese reklamiert",
            "panb": "ein Kunde Neuware kauft und diese nicht reklamiert",
            "pnab": "ein Kunde Gebrauchtware kauft und diese reklamiert",
            "pnanb": "ein Kunde Gebrauchtware kauft und diese nicht reklamiert",
            "paub": "ein Kunde Neuware kauft oder die Ware reklamiert",
            "paunb": "ein Kunde Neuware kauft oder die Ware nicht reklamiert",
            "pnaub": "ein Kunde Gebrauchtware kauft oder die Ware reklamiert",
            "pnaunb": "ein Kunde Gebrauchtware kauft oder die Ware nicht reklamiert",
        },
    ),
    # 19) Lippenstifte
    ABScenarioTemplate(
        intro="Eine Influencerin stellt ihren Followern zwei neue Lippenstifte vor: Ambition und Bonny. Sie möchte wissen, wie die beiden Lippenstifte ankommen.",
        event_a="Einem Follower gefällt Ambition.",
        event_b="Einem Follower gefällt Bonny.",
        prob_texts={
            "pa": "einem Follower Ambition gefällt",
            "pna": "einem Follower Ambition nicht gefällt",
            "pb": "einem Follower Bonny gefällt",
            "pnb": "einem Follower Bonny nicht gefällt",
            "pab": "einem Follower beide Lippenstifte gefallen",
            "panb": "einem Follower Ambition gefällt, Bonny aber nicht",
            "pnab": "einem Follower Bonny gefällt, Ambition aber nicht",
            "pnanb": "einem Follower keiner der Lippenstifte gefällt",
            "paub": "einem Follower mindestens einer der beiden Lippenstifte gefällt",
            "paunb": "einem Follower Ambition gefällt oder Bonny nicht gefällt",
            "pnaub": "einem Follower Ambition nicht gefällt oder Bonny gefällt",
            "pnaunb": "einem Follower mindestens einer der beiden Lippenstifte nicht gefällt",
        },
    ),
    # 20) Lebensmittelkonzern
    ABScenarioTemplate(
        intro="Ein Lebensmittelkonzern verschafft sich einen Überblick darüber, welche seiner Produkte biologisch und regional sind.",
        event_a="Ein Produkt ist biologisch.",
        event_b="Ein Produkt ist regional.",
        prob_texts={
            "pa": "ein Produkt biologisch ist",
            "pna": "ein Produkt nicht biologisch ist",
            "pb": "ein Produkt regional ist",
            "pnb": "ein Produkt nicht aus der Region stammt",
            "pab": "ein Produkt biologisch und regional ist",
            "panb": "ein Produkt biologisch ist aber nicht aus der Region stammt",
            "pnab": "ein Produkt nicht biologisch ist aber aus der Region stammt",
            "pnanb": "ein Produkt nicht biologisch und nicht regional ist",
            "paub": "ein Produkt biologisch oder regional ist",
            "paunb": "ein Produkt biologisch oder nicht regional ist",
            "pnaub": "ein Produkt nicht biologisch oder regional ist",
            "pnaunb": "ein Produkt nicht biologisch oder nicht regional ist",
        },
    ),
]
